### ISSUE TITLE
finding executable

### ISSUE THREAD

**Issue by aaronjensen** [jojojames/flycheck-jest#1]
This is awesome! thanks for putting this out there.

I had to make some tweaks to get it to work. 

`flycheck-jest--find-jest-project-directory` was preferring directories w/ `.npmrc`, so it found my home directory before the actual project directory.

Also, for some reason on my machine when `flycheck-jest-executable` is set to `node <path to jest.js>` flycheck claims it cannot find the executable and won't run the checker.

Making these changes seem to solve both problems:

```elisp
(defun flycheck-jest--find-jest-project-directory (&optional _checker)
  "Return directory containing project-related jest files or nil."
  (expand-file-name
   (locate-dominating-file buffer-file-name "node_modules/.bin/jest")))

(defun flycheck-jest--set-flychecker-executable ()
  "Set `flycheck-jest' executable according to jest location."
  (setq flycheck-jest-executable
        (format "%snode_modules/.bin/jest"
                (flycheck-jest--find-jest-project-directory))))
```

That said, those should probably be wrapped in a `when-let` as they error out right now if they can't find what they're looking for. This is what I use to set npm executables:

```elisp
(defun aj-javascript//locate-npm-executable (name)
  (let* ((node-module-path (concat "node_modules/.bin/" name))
         (dir (locate-dominating-file buffer-file-name node-module-path)))
    (if dir
        (concat dir node-module-path)
      (executable-find name))))

(defun aj-javascript/set-eslint-executable ()
  (interactive)
  (when-let* ((executable (aj-javascript//locate-npm-executable "eslint_d")))
    (setq-local eslintd-fix-executable executable)
    (setq-local flycheck-javascript-eslint-executable executable)))
```

**Comment by jojojames** [comment]
Thanks. I forgot to add the hook to set the executable on jest before linting starts.

I incorporated some of your suggestions (I didn't know .bin existed in node_modules :)).

If you see any other improvements, feel free to submit a PR. Extracting out the line/column number is still a pain right now (I think newer versions of jest makes it easier to pull out the line/column).
